//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D GBufferStencilTextureSampler;
//   sampler2D GBufferTextureSampler3;
//   sampler2D gDeferredLightSampler;
//   float4 gDeferredProjParams;
//   row_major float4x4 gViewInverse;
//   float4 gooDeferredLightScreenSize;
//
//
// Registers:
//
//   Name                         Reg   Size
//   ---------------------------- ----- ----
//   gViewInverse                 c12      4
//   gooDeferredLightScreenSize   c66      1
//   gDeferredProjParams          c72      1
//   gDeferredLightSampler        s0       1
//   GBufferTextureSampler3       s1       1
//   GBufferStencilTextureSampler s2       1
//

    ps_3_0
    def c0, 0.50999999, 255, -39, 1
    def c1, -0, -1, 0, 0.5
    dcl_color v0
    dcl_texcoord v1.xyw
    dcl_texcoord1 v2
    dcl_texcoord2 v3.xyw
    dcl vPos.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    add r0.xy, c0.x, vPos
    mul r0.xy, r0, c66.zwzw
    texld r1, r0, s2
    mad r0.z, r1.x, c0.y, c0.z
    add r0.z, -r0_abs.z, c0.w
    cmp r1, r0.z, c1.x, c1.y
    texkill r1
    texld r0, r0, s1
    mad r0.x, r0.x, c72.z, -c72.w
    mul r0.x, r0.x, v1.w
    rcp r0.x, r0.x
    mad r0.xy, v1, -r0.x, c15
    add r0.xy, r0, -v3
    dp2add r1.x, v2, r0, c1.z
    dp2add r1.y, v2.zwzw, r0, c1.z
    mul r0.x, c1.w, v3.w
    mad r0.xy, r1, r0.x, c1.w
    texld r0, r0, s0
    mul oC0, r0, v0

// approximately 21 instruction slots used (3 texture, 18 arithmetic)

