//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D gDeferredLightSampler;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   gDeferredLightSampler s0       1
//

    ps_3_0
    def c0, 0.333332986, 1, 0, 0
    dcl_texcoord v0.xy
    dcl_color v1.w
    dcl_2d s0
    texld r0, v0, s0
    dp3 r0.x, r0, c0.x
    mul oC0.w, r0.x, v1.w
    mov oC0.xyz, c0.y

// approximately 4 instruction slots used (1 texture, 3 arithmetic)

