//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
    ps_3_0
    def c0, 1, 0, 0, 0
    dcl_texcoord v0.xyz
    mad oC0, v0.xyzx, c0.xxxy, c0.yyyx

// approximately 1 instruction slot used

