//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   sampler2D gDeferredLightSampler;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   gDeferredLightSampler s0       1
//

    ps_3_0
    def c0, 1, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xyz
    dcl_2d s0
    texld r0, v0, s0
    mul oC0.xyz, r0, v1
    mov oC0.w, c0.x

// approximately 3 instruction slots used (1 texture, 2 arithmetic)

