//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
    vs_3_0
    def c0, 2, 0, -1, 1
    dcl_position v0
    dcl_position o0
    mad o0, v0.xyxx, c0.xxyy, c0.zzyw

// approximately 1 instruction slot used

