//
// Generated by Microsoft (R) HLSL Shader Compiler 9.26.952.2844
//
// Parameters:
//
//   float4 debugLightColour;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   debugLightColour c66      1
//

    ps_3_0
    dcl_texcoord v0
    mul oC0, c66, v0

// approximately 1 instruction slot used

